resources:
- ../../base
namespace: staging
namePrefix: stg-
images:
- name: acrabcreg2026test.azurecr.io/backend
  newTag: f8fb01bac5812c5235c1f631d9217e1e1307057b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
