apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
    
resources:
- ../../base

namespace: production
namePrefix: prd-
images:
- name: acrabcreg2026test.azurecr.io/backend
  newTag: 6955cbe09263b2ad51b718b6df7e411e5c291a52
# nur in der Produktion soll die Anzahl der Replikas auf 3 erhöht werden
patches:
  - path: patch-replicas.yaml
    
  - target:
        kind: Ingress
        name: backend-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /prod